name: Push to Dockerhub

on:
  push:
    paths:
      - '.github/workflows/build.yaml'
      - 'resources/**'
      - 'docker/**'
      - '.dockerignore'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to Docker Hub'
        uses: 'docker/login-action@v3'
        with:
          username: 'dancarbone'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'

      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@v3'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Build and push'
        uses: 'docker/build-push-action@v6'
        with:
          file: 'docker/Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          sbom: true
          provenance: 'mode=max'
          tags: 'dancarbone/php-fhir-test-server:latest'